{% set version = "0.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-printr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/printr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/printr/printr_{{ version }}.tar.gz
  sha256: 3dc669fbae768ccc616b44a6ebae28347bb55a449af00d8679179d7d1d9f1ef7

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-knitr >=1.16
  run:
    - r-base
    - r-knitr >=1.16

test:
  commands:
    - $R -e "library('printr')"           # [not win]
    - "\"%R%\" -e \"library('printr')\""  # [win]

about:
  home: https://yihui.name/printr
  license: GPL-2.0-or-later
  summary: Extends the S3 generic function knit_print() in 'knitr' to automatically print some objects using an appropriate format such as Markdown or LaTeX. For example, data frames are automatically printed as tables, and the help() pages can also be rendered in 'knitr' documents.
  license_family: GPL
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
