appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: fHxtuBaJh6LAkgO/iJFE6myP+4QrPmwe7zSDimKv+x+D9FDcWsOkEHMCrtAiAg+UnheqfMTGLiPxYZz4ytkVzeoREvnlb9b86X/iFLWX0r+/n8CGFtOjvy8nP9Q08y4oKkSZWw11nklA/j8bLxS0/VELe+MaM/oaUFQC1S2asgR3oecDwxGvVaD/chJPWvFZeRUtFqwZ8Lha313zpwz5UnrvhdkCFAp5uhQdoyRG/nlMlb9oBDu3bApYsiXaguMFYzN2R7w+Z7FX0CPoie2eNrfVgMqOewDtn47//58zeMlOGWTBCz5k0FBCfreGQBfG2F9GiucUyUKTDCpKrED/Y8izk0R2oF19+F1J6vziTlWOXaIdDeZ0wkDnXLnmNWcFoBOsAP+EiP5rjAFGPrq7xyL+9WHzr+Lj1YcN6A7AU4PakLLuSTMbA/MB9NrHbKZ93LttAUY6rR361CA7OFlcDnKEnFxJWPq92qetH4AlLbcoMo/ueVVq724c/l/GUExvuoiEa+OfE13f5RY5wZ16iBZlfSjJUjtf6qWYILBOg94EvWOiLstRwobOEoeX6A27OAKHnDd/R3uomFmHLy3yteiy8FBSw9z9YObqr26hgkG9iRwF0mofcTo74h0H9AZAR7TLeSeiJOnPrW5WhlkzewQ7ikpgoeMMa+0JTBVFQkQ=
